name: 'SendGrid E-Mail Action'
description: 'Send emails using SendGrid on actions'
branding:
    icon: 'message-square'
    color: 'blue'
inputs:
    sendgrid-token:
        description: 'The token for sendgrid'
        required: true
    to:
        description: 'The receivers ( can be only one ) that the email will go, seperated by the comma (,) character'
        required: true
    from:
        description: 'The email that will be shown as sender'
        required: false
        default: 'sendgridmailaction@github.com'
    subject:
        description: 'The subject of the email'
        required: false
        default: 'GitHub action notification'
    text:
        description: 'The body of the mail as Plain Text'
        required: false
        default: ""
    html:
        description: 'The body of the mail as HTML'
        required: false
        default: ""
    attachments:
        description: 'Comma seperated list of files which should be attached to the e-mail'
        required: false
        default: ""
runs:
    using: 'node16'
    main: 'out/index.js'
